branches:
  only:
    - master

environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    FEATURES: " "
  - TARGET: i686-pc-windows-msvc
    FEATURES: " "
  - TARGET: i686-pc-windows-gnu
    FEATURES: " "
  - TARGET: x86_64-pc-windows-msvc
    FEATURES: "winrt"
  - TARGET: i686-pc-windows-gnu
    FEATURES: "winrt"
  - TARGET: x86_64-pc-windows-gnu
    FEATURES: "winrt"
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose --features "%FEATURES%"

test_script:
  - cargo test --features "%FEATURES%"
  - cargo build --features "%FEATURES%" --example test_list_ports
