jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
#      beta:
#        rustup_toolchain: beta
#      nightly:
#        rustup_toolchain: nightly
  steps:
  - ${{ if not(startsWith(parameters.name, 'Windows')) }}:
    # Linux and macOS.
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "##vso[task.setvariable variable=PATH;]$PATH"
      displayName: Install Rust
  - ${{ if startsWith(parameters.name, 'Linux') }}:
    # Linux only.
    - script: |
        sudo apt-get update && sudo apt-get install -y libasound2-dev libjack-jackd2-dev
      displayName: Install ALSA and Jack dependencies
  - ${{ if startsWith(parameters.name, 'Windows') }}:
    # Windows.
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
      displayName: Install Rust (Windows)
  # All platforms.
  - script: |
        rustc -Vv
        cargo -V
    displayName: Query installed versions
  - bash: cargo build --verbose
    displayName: Build