[package]
name = "midir"
version = "0.1.2"
authors = ["Patrick Reisert"]
description = "A cross-platform, realtime MIDI processing library, inspired by RtMidi."
repository = "https://github.com/Boddlnagg/midir"
readme = "README.md"
keywords = ["midi", "audio", "music", "sound"]
license = "MIT"

[features]
default = []
avoid_timestamping = []
jack = ["jack-sys"]

[dependencies]
bitflags = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
alsa-sys = "0.0.8"
libc = "0.2.7"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.4"
winmm-sys = "0.2.0"

[dependencies.jack-sys]
version = "0.1.0"
optional = true
